# Generated by Django 4.0.1 on 2022-01-22 18:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Order Confirmed', 'Order Confirmed'), ('Preparing', 'Preparing'), ('Picked by courier', 'Picked by courier'), ('Canceled', 'Canceled'), ('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='companyName',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{1,11}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pricePerKg',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
