# Generated by Django 4.0.1 on 2022-01-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_status_profile_companyname_alter_profile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='companyName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
