# Generated by Django 4.0.1 on 2022-01-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_profile_companyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='companyName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pricePerKg',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
