# Generated by Django 4.0.1 on 2022-01-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_profile_priceperkg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pricePerKg',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
