# Generated by Django 4.0.1 on 2022-01-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_profile_companyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='companyName',
            field=models.CharField(default='Non', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pricePerKg',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
