# Generated by Django 4.0.1 on 2022-01-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_profile_companyname_alter_profile_priceperkg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
