# Generated by Django 4.0.1 on 2022-01-26 00:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rate',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.DeleteModel(
            name='OrderRate',
        ),
    ]
