# Generated by Django 4.0.1 on 2022-01-26 00:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_order_rate_delete_orderrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fName',
            field=models.CharField(default='First Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lName',
            field=models.CharField(default='Last Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,11}$')]),
        ),
    ]
